name: xsd_to_dart_code_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  change_case: ^2.2.0
  collection: ^1.19.1
  dart_code: ^0.2.2
  logging: ^1.3.0
  path: ^1.9.1
  xml: ^6.6.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
